services:
  - type: web
    name: andres-play
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        value: dpg-d90pv7cm0tmc73e1l5ag-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: andres_stream_db
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: OPENAI_API_KEY
        sync: false
