server.port=8080

langchain4j.open-ai.chat-model.model-name=gpt-4o-mini
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.opem-ai.chat-model.log-response=true
loggin.level.dev.langchain4j=DEBUG
loggin.level.dev.ai4j.openai4j=DEBUG

#Spring data
spring.datasource.url=jdbc:postgresql://localhost:5432/andres_stream_db
spring.datasource.username=andresian
spring.datasource.password=andresian1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always