spring.profiles.active=dev
spring.application.name=andres-play
server.servlet.context-path=/andres-stream/api
langchain4j.open-ai.chat-model.api-key=demo

#Spring data
spring.datasource.driver-class-name=org.postgresql.Driver

